# Generated by Django 5.1.7 on 2025-03-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tick',
            new_name='ticketModel',
        ),
    ]
