# Generated by Django 5.1.7 on 2025-03-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_rename_tick_ticketmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ticketModel',
            new_name='ticket',
        ),
    ]
