# Generated by Django 5.1.7 on 2025-03-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_user_efresh_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='efresh_token',
            new_name='refresh_token',
        ),
    ]
