# Generated by Django 5.1.7 on 2025-03-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_ticket_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.CharField(choices=[('service1', 'service1'), ('service2', 'service2'), ('service3', 'service3')], max_length=100, null=True),
        ),
    ]
