# Generated by Django 5.1.7 on 2025-03-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
