# Generated by Django 5.1.7 on 2025-03-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_remove_user_refresh_token'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertoken',
            table='user_token',
        ),
    ]
