# Generated by Django 5.1.7 on 2025-03-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_ticket_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='np', max_length=150),
            preserve_default=False,
        ),
    ]
