# Generated by Django 5.1.7 on 2025-03-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_remove_user_is_staff_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
