# Generated by Django 5.1.7 on 2025-03-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
