# Generated by Django 5.1.7 on 2025-03-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('résolu', 'résolu'), ('en_cours', 'En cours'), ('annuler', 'Annuler')], default='ouvert', max_length=50),
        ),
    ]
