# Generated by Django 5.1.7 on 2025-03-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_user_access_token_user_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
