# Generated by Django 5.1.7 on 2025-03-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_ticket_is_deleted_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', null=True),
        ),
    ]
