# Generated by Django 5.1.7 on 2025-03-21 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='personne_declarer',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
