# Generated by Django 5.1.7 on 2025-03-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
