# Generated by Django 5.1.7 on 2025-03-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('en_attent', 'En attent'), ('resolu', 'Résolu'), ('en_cours', 'En cours'), ('annuler', 'Annuler')], default='en_attent', max_length=50),
        ),
    ]
