# Generated by Django 5.1.7 on 2025-03-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
