# Generated by Django 5.1.7 on 2025-04-01 18:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0020_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png', max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
